spring.application.name=social_media_system

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=socialMediaSystemDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_USERPW